spring.application.name=LostAndFound

server.port=

spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://<DB_URL>:3306/<DB_NAME>?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.hikari.username=<DB_USER>
spring.datasource.hikari.password=<DB_PASS>
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

spring.web.resources.static-locations=<FILE_PATH>
file.upload-path=<FILE_PATH>


